export default function Index () {
	return (
		<section>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In eget ipsum sodales, pharetra quam nec, blandit lorem. Phasellus ultrices varius risus, vel vestibulum quam congue at. Aenean rutrum fermentum ipsum eget luctus. Donec sit amet cursus lacus, quis consectetur sapien. Nunc sodales elit nec facilisis blandit. Sed cursus neque eget efficitur maximus. Sed ullamcorper tortor ac augue bibendum euismod. Maecenas placerat, est ut fringilla elementum, arcu odio rutrum leo, a venenatis libero ante eu neque. Duis sit amet lacinia massa, in varius urna. Integer venenatis nunc semper nunc laoreet, in facilisis nisi consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque iaculis leo eget turpis suscipit, vel lobortis felis iaculis. Praesent pretium ultricies est, nec condimentum quam ornare et. Duis molestie dui velit, sit amet ultricies turpis pretium mollis.</p>
			<p>Phasellus eu sollicitudin sem. Maecenas dignissim vestibulum venenatis. Cras elementum interdum mi in varius. Curabitur a dui orci. Aenean quis metus ipsum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla efficitur elit vitae posuere consectetur. Proin posuere ante vitae eros tincidunt, hendrerit luctus dui scelerisque. Praesent ac justo at lorem cursus interdum. Nunc at placerat elit. Proin ullamcorper sapien vel ante commodo pharetra. Pellentesque vestibulum nunc et risus bibendum, eget ultricies quam malesuada. Phasellus id justo odio. Donec pretium non lacus id dapibus. Phasellus eu turpis commodo, sollicitudin lacus eget, tempus urna.</p>
			<p>In hac habitasse platea dictumst. Fusce laoreet orci vel sodales aliquet. Mauris finibus lorem quis semper volutpat. Duis nunc felis, condimentum non ornare quis, egestas ut mi. Vestibulum ultrices ligula metus, a congue purus auctor vel. Donec pretium nisi nulla, at ornare nunc bibendum vel. Nullam eu mauris sagittis, rutrum erat fermentum, venenatis quam.</p>
			<p>Suspendisse velit orci, varius et sapien ornare, sollicitudin dictum diam. Quisque lectus massa, aliquam sed metus ornare, scelerisque tincidunt elit. Donec quis arcu quis purus posuere laoreet et non neque. Vivamus fermentum at ipsum non interdum. Ut condimentum iaculis dui non ultrices. Sed tempor dui nisi, quis aliquet erat egestas ac. Nam accumsan ipsum quis neque iaculis, et pretium dui scelerisque. Pellentesque sapien libero, tempus vitae erat sit amet, congue porta neque. Fusce semper ullamcorper aliquet. Proin ut lorem ante. Nam hendrerit velit elit, non egestas ex commodo sit amet. Integer orci massa, fermentum ac odio a, ultrices commodo sem. Proin accumsan porttitor ipsum. Vivamus non felis quis odio tempus sollicitudin. Nulla sit amet augue libero. Aenean lacinia tellus a enim ultricies consequat.</p>
			<p>Quisque sed libero eu nisi dapibus tincidunt eu nec massa. Suspendisse potenti. Nam ut malesuada nibh. Vestibulum in scelerisque ante. Ut egestas ligula sed libero condimentum, vitae rhoncus ex posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut consequat porttitor dolor, ultricies semper ex gravida nec. Aliquam ut molestie nulla. Praesent eget commodo dui, eu porttitor erat. Nam et commodo lectus, vitae maximus metus. Fusce vel magna enim. Nulla vitae mi bibendum nisl elementum dapibus.</p>
		</section>
	)
}
